# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: caruychen <cchen@student.hive.fi>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/05 17:18:25 by caruychen         #+#    #+#              #
#    Updated: 2022/09/05 23:16:16 by caruychen        ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME := asm

include src.mk
include ../directives/obj.mk
include ../directives/libft.mk
include ../directives/flags.mk
include ../directives/rules.mk
