# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: caruychen <cchen@student.hive.fi>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/05 16:56:16 by caruychen         #+#    #+#              #
#    Updated: 2022/09/05 23:17:34 by caruychen        ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME := corewar

include src.mk
include ../directives/obj.mk
include ../directives/libft.mk
include ../directives/flags.mk
include ../directives/rules.mk
